### ISSUE TITLE
Why set default alertmanager config route to "group_by=[...]"  

### ISSUE THREAD

**Issue by anish-mudaraddi** [azimuth-cloud/capi-helm-charts#460]
what's the purpose of setting `group_by: [...]` by default for alertmanager config?

https://github.com/azimuth-cloud/capi-helm-charts/blob/main/charts/cluster-addons/templates/monitoring/kube-prometheus-stack.yaml#L41-L44

I want to write config to just group by "service" and "cluster" - so I can send 1 alert which groups multiple prometheus alerts 
 - but I can't because "..." is added by default and it conflicts with my config

**Comment by sd109** [comment]
Does using the following in your Helm values not override the default group_by list?
```yaml
      config:
        route:
          group_by: 
          - service
          - cluster
```
